name: Run Maven Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Ejecutar tests de Maven
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar y ejecutar tests
        run: mvn -B clean test
